version: "3.7"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "postgres_password"
      POSTGRES_DB: "postgres_db"
    ports:
      - 5433:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
 
volumes:
  pg_data: