version: 2

models:
  - name: customer_revenue_by_month
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - customer_id
            - date_month

  - name: customer_churn_month
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
